spring:
  flyway:
    url: jdbc:postgresql://bookshop-postgres/bookshopdb_delivery
  r2dbc:
    url: r2dbc:postgresql://bookshop-postgres/bookshopdb_delivery
  rabbitmq:
    host: bookshop-rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bookshop-keycloak/realms/PolarBookshop