apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  type: ClusterIP
  selector:
    app: delivery-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9006
